# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AutoInsight blog
logo: logo.png
email: hi@savy.tw
description: > # this means to ignore newlines until "baseurl:"
  Download AutoInsight app to help you shop for used cars.  Get VinAudit history report, 
  car appraisal, and diagnose your car while you test drive.  Know your car before you buy it!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://autoinsight.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
